### ISSUE TITLE
Missing dependency on HTML::TreeBuilder::LibXML ?

### ISSUE THREAD

**Issue by GeJ** [tokuhirom/Web-Query#36]
I tried to upgrade this localtime() and something went sideways : 
t/next_until.t complained that test 6 (out of 10) borked and that I planned 10 tests and only ran 5.
Looking at the code, it doesn't seem to be any different than t/next.t (which ran just fine).

I ran a simple `perl -Ilib -MWeb::Query::LibXML -E 'say $Web::Query::LibXML::VERSION'` and perl complained it couldn't find HTML::TreeBuilder::LibXML. I cpanm'd it, and retried to update Web::Query and everything went fine.

Why only this test failed is beyond me. I didn't investigate any further yet because of $dayjob but I'll try to have a look at it later. Just thought to report it if anyone had the same issue.

For the record, `perl -v` says :

> This is perl 5, version 20, subversion 2 (v5.20.2) built for amd64-freebsd-thread-multi

and all my packages are up-to-date as far as cpan-outdated is concerned.

**Comment by yanick** [comment]
Weeeird. All the tests, I think, have the same conditional test for libxml. I'll try to look at that tonight. Thanks!

**Comment by GeJ** [comment]
Ha!

Could it be that on line 4 you have : 
> use Test::More tests => 10;

All the other tests seem to `use Test::More;` and let it figure out how many tests it needs to run wether libxml is available or not.

On a side note, github.com doesn't seem to show your latest changes, did you switch to another repo?

**Comment by GeJ** [comment]
huh, never mind the github.com question, it seems that the 'tagged' versions are just ahead of the master branch.

**Comment by yanick** [comment]
Yeah, this distribution is not under my usual dzil workflow. I'll push the new master soon. Meanwhile, a new version is on github. :-)
