### ISSUE TITLE
Additional methods

### ISSUE THREAD

**Issue by mewsoft** [tokuhirom/Web-Query#37]
Congratulations on this fantastic module, really bringing the ease of DOM treatment to Perl.

A quick suggestion to add some shortcut methods that we all heavily use in jQuery that I'd like
to be added to this module:

# get element id direct
my $id = $q->id;
instead of my $id = $q->attr("id");

# get element name direct
my $name = $q->name;
instead of my $name = $q->attr("name");

# treat the data attribute in a special way like jQuery
my $ = $q->data("custom");
instead of $q->attr("data-custom");
$q->data("custom", "value"); # set

my $class = $q->class;
instead of my $class = $q->attr("class");

# toggle classes like jQuery
$q->toggle_class($class); # space separated class names

Also how comments are treated here.

Thank you again for nice work and sorry if my post is trivial.

**Comment by yanick** [comment]
Thank you for the kind words. And good suggestions. I'm (slowly) trying to bring Web::Query in-line with jQuery, but most as-I-need-it basis. Those are all good utility functions to have. I'll add them to the list of things to do. :-)

**Comment by yanick** [comment]
There. All implemented. Enjoy! :-)

**Comment by mewsoft** [comment]
Perfect!!!.
