### ISSUE TITLE
Processing instructions?

### ISSUE THREAD

**Issue by remorse** [tokuhirom/Web-Query#49]
Hi! Is there a way that I can ask Web::Query to find all XML processing instructions in a document?

**Comment by yanick** [comment]
At it is right now, not really, but as Web::Query::LibXML is based on LibXML, adding a '#pi' pseudo-node should not be too hard. I'm going to keep that ticket as a reminder for that task.

**Comment by yanick** [comment]
Adding some documentation about this in the pod of Web::Query:

=head2 How to find XML processing instructions in a document?

It's possible with L<Web::Query::LibXML> and by using an xpath expression
with C<find()>:

    # find <?xml-stylesheet ... ?>
    $q->find(\"//processing-instruction('xml-stylesheet')");

However, note that the support for processing instructions 
in L<HTML::TreeBuilder::LibXML::Node> is sketchy, so there
are methods like C<attr()> that won't work.

**Comment by yanick** [comment]
Mah pleasure. :-)
